import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.JButton;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JTextField;
/**
 *
 * @author librecht kuijvenhoven
 */
public class layout extends passwordGenerator{

    // Variables declaration - do not modify
    private javax.swing.JCheckBox characters;
    private javax.swing.JButton copy;
    private javax.swing.JButton jButton1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextPane password_field;
    private javax.swing.JTextPane password_length;
    private javax.swing.JTextField length;
    private javax.swing.JCheckBox lower;
    private javax.swing.JCheckBox numbers;
    private javax.swing.JCheckBox symbols;
    private javax.swing.JCheckBox upper;

    passwordGenerator pw;
    // End of variables declaration
    public layout() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        password_field = new javax.swing.JTextPane();
        password_length = new javax.swing.JTextPane();
        jButton1 = new javax.swing.JButton();
        lower = new javax.swing.JCheckBox();
        upper = new javax.swing.JCheckBox();
        numbers = new javax.swing.JCheckBox();
        characters = new javax.swing.JCheckBox();
        symbols = new javax.swing.JCheckBox();
        length = new javax.swing.JTextField();
        copy = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jScrollPane1.setViewportView(password_field);

        password_length.setEditable(false);
        password_length.setBackground(new java.awt.Color(240, 240, 240));
        password_length.setText("Output:");

        jButton1.setText("Generate!");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        lower.setText("lowercase letters");
        lower.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lowerActionPerformed(evt);
            }
        });

        upper.setText("uppercase letters");
        upper.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                upperActionPerformed(evt);
            }
        });

        numbers.setText("numbers");
        numbers.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numbersActionPerformed(evt);
            }
        });

        characters.setText("special characters");
        characters.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                charactersActionPerformed(evt);
            }
        });

        symbols.setText("symbols");
        symbols.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                symbolsActionPerformed(evt);
            }
        });

        length.setText("6");
        copy.setText("copy");
        copy.setVisible(false);
        copy.addActionListener(new java.awt.event.ActionListener(){
            public void actionPerformed(java.awt.event.ActionEvent evt){ copyActionPreformed(evt); }
        });
        //<editor-fold desc="grouplayout">
        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGap(52, 52, 52)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(password_length, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(length, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                        .addGroup(layout.createSequentialGroup()
                                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                        .addComponent(lower)
                                                                        .addComponent(upper)
                                                                        .addComponent(symbols))
                                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                        .addGroup(layout.createSequentialGroup()
                                                                                .addGap(70, 70, 70)
                                                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                                        .addComponent(numbers)
                                                                                        .addComponent(characters)))
                                                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 171, Short.MAX_VALUE)
                                                                                .addComponent(jButton1))))
                                                        .addGroup(layout.createSequentialGroup()
                                                                .addComponent(jScrollPane1)
                                                                .addGap(18, 18, 18)
                                                                .addComponent(copy, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                                .addGap(59, 59, 59))))
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(24, 24, 24)
                                .addComponent(password_length, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(copy, javax.swing.GroupLayout.DEFAULT_SIZE, 42, Short.MAX_VALUE)
                                        .addComponent(jScrollPane1))
                                .addGap(21, 21, 21)
                                .addComponent(length, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(lower)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(upper)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(symbols))
                                        .addGroup(layout.createSequentialGroup()
                                                .addGap(11, 11, 11)
                                                .addComponent(numbers)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(characters, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(jButton1)))
                                .addGap(32, 32, 32))
        );// </editor-fold>
        pack();
    }// </editor-fold>

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {

        pw.pwLength = Integer.parseInt(length.getText());
        // checks if the password field is empty
        if(password_field.getText() != null && password_field.getText().equals("")) {
            if(pw.passwordCheck() == "checked") {
                display(generate_password());
                copy.setVisible(true);
            }else {
                copy.setVisible(false);
                display(passwordCheck());
            }
        }else {
            if(pw.passwordCheck() == "checked") {
                password_field.setText("");
                display(generate_password());
                copy.setVisible(true);
            }else {
                copy.setVisible(false);
                display(passwordCheck());
            }
        }

    }

    private void lowerActionPerformed(java.awt.event.ActionEvent evt) {
        if(lower.isSelected()) {
            pw.useLower = true;
        }else{
            pw.useLower = false;
        }
    }

    private void upperActionPerformed(java.awt.event.ActionEvent evt) {
        if(upper.isSelected()) {
            pw.useUpper = true;
        }else{
            pw.useUpper = false;
        }
    }

    private void numbersActionPerformed(java.awt.event.ActionEvent evt) {
        if(numbers.isSelected()) {
           pw.useNumbers = true;
        }else{
            pw.useNumbers = false;
        }
    }

    private void charactersActionPerformed(java.awt.event.ActionEvent evt) {
        if(characters.isSelected()) {
            pw.useCharacters = true;
        }else{
            pw.useCharacters = false;
        }
    }

    private void symbolsActionPerformed(java.awt.event.ActionEvent evt) {
        if(symbols.isSelected()) {
            pw.useSymbols = true;
        }else{
            pw.useSymbols = false;
        }
    }
    private void copyActionPreformed(java.awt.event.ActionEvent evt){
        pw.Copy();
    }
    private void display(String text){
        password_field.setText(text);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(layout.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(layout.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(layout.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(layout.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new layout().setVisible(true);
            }
        });
    }
}